openapi: 3.1.0
info:
  title: AUTOTRACKER API
  description: API сервиса отслеживания марщрутов AutoTracker
  license:
    name: ''
  version: 0.1.0
servers:
  - url: http://127.0.0.1:9887
    description: Local server
  - url: http://{url}:9887
    description: Local network API
    variables:
      url:
        default: 0.0.0.0
        description: Default local network
paths:
  /api/v2/cameras/{id}:
    get:
      tags:
        - camera
      summary: Получение камеры
      description: Получение камеры по id
      operationId: handle_get_camera_by_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Камера успешно получена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CameraResponse'
        '404':
          description: Камера не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CameraResponse'
              example:
                camera: null
                status:
                  code: 4002
                  message: camera not found
        '500':
          description: Внутренняя ошибка сервера
    delete:
      tags:
        - camera
      summary: Удаление камеры
      description: Удаление камеры по id
      operationId: handle_delete_camera_by_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Камера успешно удалена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CameraResponse'
        '404':
          description: Камера не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CameraResponse'
              example:
                camera: null
                status:
                  code: 4002
                  message: camera not found
        '500':
          description: Внутренняя ошибка сервера
  /api/v2/cameras:
    post:
      tags:
        - camera
      summary: Добавление камеры
      description: Получение камеры по id
      operationId: handle_add_camera
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Camera'
        required: true
      responses:
        '200':
          description: Камера успешно получена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWithoutData'
        '500':
          description: Внутренняя ошибка сервера
    get:
      tags:
        - camera
      summary: Получение камеры
      description: Получение камеры по id
      operationId: handle_get_cameras
      responses:
        '200':
          description: Камера успешно получена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CameraResponse'
        '404':
          description: Камера не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CameraResponse'
              example:
                camera: null
                status:
                  code: 4002
                  message: camera not found
        '500':
          description: Внутренняя ошибка сервера
  /api/v2/cars/route:
    post:
      tags:
        - route
      summary: Получение маршрута
      description: Получение маршрута по гос.номеру и дате
      operationId: handle_route
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouteRequest'
        required: true
      responses:
        '200':
          description: Маршрут успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RouteResponse'
        '500':
          description: Внутренняя ошибка сервера
  /api/v2/cars/search:
    post:
      tags:
        - search
        - car
      summary: Поиск автомобилей
      description: Поиск автомобилей по общим фильтрам
      operationId: handle_search_cars_by_filters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchCarByFilterRequest'
        required: true
      responses:
        '200':
          description: Автомобили успешно найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarSearcherResponse'
        '500':
          description: Внутренняя ошибка сервера
  /api/v2/snaps:
    post:
      tags:
        - snap
      summary: Отравление снимка
      description: Отравление снимка автомобиля
      operationId: handle_snap_send
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnapSendRequest'
        required: true
      responses:
        '201':
          description: Снимок успешно добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWithoutData'
        '400':
          description: Некорректные входные параметры
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWithoutData'
        '500':
          description: Внутренняя ошибка сервера
  /api/v2/track-infos/search:
    post:
      tags:
        - search
        - track-info
      summary: Поиск отслеживаний
      description: Поиск отслеживаний по общим фильтрам
      operationId: handle_search_track_info_by_filters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchTrackInfoByFilterRequest'
        required: true
      responses:
        '200':
          description: Информация об отслеживании успешно найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackInfoSearcherResponse'
        '500':
          description: Внутренняя ошибка сервера
  /api/v2/users/auth:
    post:
      tags:
        - auth
      summary: Аутентификация
      description: Аутентификация пользователя по логину и паролю
      operationId: handle_auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: true
      responses:
        '200':
          description: Пользователь успешно авторизирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '500':
          description: Внутренняя ошибка сервера
  /api/v2/users/{id}/passport:
    patch:
      tags:
        - auth
      summary: Подтверждениее пасспортных данных
      description: Подтверждениее пасспортных данных пользователя
      operationId: handle_passport_conf
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
        required: true
      responses:
        '204':
          description: Пользователь успешно обновил паспортные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWithoutData'
        '500':
          description: Внутренняя ошибка сервера
  /api/v2/users/registr:
    post:
      tags:
        - auth
      summary: Регистрация
      description: Регистрация нового пользователя
      operationId: handle_reg
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegRequest'
        required: true
      responses:
        '200':
          description: Пользователь успешно зарегестрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWithoutData'
        '500':
          description: Внутренняя ошибка сервера
components:
  schemas:
    AuthRequest:
      type: object
      required:
        - email
        - pswd
      properties:
        email:
          type: string
          example: email@example.com
        pswd:
          type: string
          example: password
    AuthResponse:
      type: object
      required:
        - status
        - user
      properties:
        status:
          $ref: '#/components/schemas/StatusResponse'
        user:
          $ref: '#/components/schemas/User'
    Camera:
      type: object
      required:
        - id
        - is_radar
        - location
      properties:
        id:
          type: integer
          example: 1
          minimum: 0
        is_radar:
          type: boolean
          example: true
        location:
          $ref: '#/components/schemas/Location'
    CameraResponse:
      type: object
      required:
        - status
        - camera
      properties:
        camera:
          $ref: '#/components/schemas/Camera'
        status:
          $ref: '#/components/schemas/StatusResponse'
    Car:
      type: object
      required:
        - owner_fio
        - gos_num
        - model
        - mark
        - color
        - year
        - vin
        - sts
        - pts
      properties:
        color:
          type: string
        gos_num:
          type: string
        mark:
          type: string
        model:
          type: string
        owner_fio:
          type: array
          items: false
          prefixItems:
            - type: string
            - type: string
            - type:
                - string
                - 'null'
        pts:
          $ref: '#/components/schemas/Document'
        sts:
          $ref: '#/components/schemas/Document'
        vin:
          type: string
        year:
          type: integer
          format: int32
          minimum: 0
    CarSearcherResponse:
      type: object
      required:
        - status
        - cars
      properties:
        cars:
          type: array
          items:
            $ref: '#/components/schemas/Car'
          example: []
        cursor:
          type: integer
          format: int64
          minimum: 0
          example: 100
        status:
          $ref: '#/components/schemas/StatusResponse'
    Document:
      type: object
      required:
        - serial
        - number
      properties:
        number:
          type: string
          example: '111111'
        serial:
          type: string
          example: '1111'
    Location:
      type: object
      required:
        - longitude
        - latitude
      properties:
        latitude:
          type: number
          format: double
          example: 53.9333
        longitude:
          type: number
          format: double
          example: 53.9222
    PassportConfRequest:
      type: object
      required:
        - email
        - passport
      properties:
        email:
          type: string
          example: exist@exist.com
        passport:
          $ref: '#/components/schemas/Document'
    PointData:
      type: object
      required:
        - cords
      properties:
        cords:
          $ref: '#/components/schemas/Location'
        speed:
          type:
            - integer
            - 'null'
          format: int32
          example: 60
          minimum: 0
    RegRequest:
      type: object
      required:
        - firstname
        - surname
        - email
        - pswd
        - rep_pswd
      properties:
        email:
          type: string
          example: email@example.com
        firstname:
          type: string
          example: firstname
        lastname:
          type:
            - string
            - 'null'
          example: lastname
        pswd:
          type: string
          example: password
        rep_pswd:
          type: string
          example: password
        surname:
          type: string
          example: surname
    ResponseWithoutData:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/StatusResponse'
    Role:
      type: string
      enum:
        - user
        - operator
        - audit
    RouteRequest:
      type: object
      required:
        - user_login
        - gos_num
        - date
      properties:
        date:
          type: string
          example: 01.01.2025
        gos_num:
          type: string
          example: А777МР77
        user_login:
          type: string
          example: example@example.com
    RouteResponse:
      type: object
      required:
        - status
      properties:
        route:
          type:
            - array
            - 'null'
          items:
            $ref: '#/components/schemas/PointData'
        status:
          $ref: '#/components/schemas/StatusResponse'
    SearchCarByFilterRequest:
      type: object
      required:
        - passport
      properties:
        gos_num:
          type:
            - string
            - 'null'
          example: А*23**99
        lastname:
          type:
            - string
            - 'null'
          example: lastname
        name:
          type:
            - string
            - 'null'
          example: name
        passport:
          $ref: '#/components/schemas/Document'
        surname:
          type:
            - string
            - 'null'
          example: surname
        cursor:
          type:
            - int
            - 'null'
          example: 0
        limit:
          type:
            - int
            - 'null'
          example: 100
    SearchTrackInfoByFilterRequest:
      type: object
      required:
        - passport
      properties:
        date:
          type:
            - string
            - 'null'
          example: 01.01.2025
        gos_num:
          type:
            - string
            - 'null'
          example: А*23**99
        lastname:
          type:
            - string
            - 'null'
          example: lastname
        name:
          type:
            - string
            - 'null'
          example: name
        passport:
          $ref: '#/components/schemas/Document'
        surname:
          type:
            - string
            - 'null'
          example: surname
        cursor:
          type:
            - int
            - 'null'
          example: 0
        limit:
          type:
            - int
            - 'null'
          example: 100
    SnapSendRequest:
      type: object
      required:
        - time
        - date
        - gos_num
        - camera
        - camera_id
      properties:
        camera_id:
          type: integer
          example: 1
          minimum: 0
        date:
          type: string
          example: 01.01.2025
        gos_num:
          type: string
          example: А777МР77
        speed:
          type:
            - integer
            - 'null'
          format: int32
          example: 70
          minimum: 0
        time:
          type: string
          example: '8:10'
    StatusResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 0
        message:
          type: string
          example: OK
    TrackInfo:
      type: object
      required:
        - track_time
        - route_date
        - car
        - user
      properties:
        car:
          $ref: '#/components/schemas/Car'
        route_date:
          type: string
        track_time:
          type: string
        user:
          $ref: '#/components/schemas/User'
    TrackInfoSearcherResponse:
      type: object
      required:
        - status
        - track_info
      properties:
        track_info:
          type: array
          items:
            $ref: '#/components/schemas/TrackInfo'
          example: []
        cursor:
          type: integer
          format: int64
          minimum: 0
          example: 100
    User:
      type: object
      required:
        - name
        - surname
        - email
        - role
        - is_verified
      properties:
        email:
          type: string
          example: email@example.ru
        is_verified:
          type: boolean
          example: true
        lastname:
          type:
            - string
            - 'null'
          example: Ivanovich
        name:
          type: string
          example: Ivan
        passport:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/Document'
        role:
          $ref: '#/components/schemas/Role'
        surname:
          type: string
          example: Ivanov
tags:
  - name: route
    description: Получение маршрута
  - name: auth
    description: Авторизация
  - name: snap
    description: Снимки
  - name: search
    description: Поисковик
  - name: car
    description: Автомобили
  - name: camera
    description: Камера
  - name: track-info
    description: Информация об отслеживании

